### ISSUE TITLE
[Feedback] Contadores ilimitados para un usuario

### ISSUE THREAD

**Issue by Goferk** [stesoftware/portal_fisica#29]
Cada alumno debe ser capaz de dar like o dislike solo una vez a cada contenido, en la tabla de feedback debería ser clave compuesta única entre el id del contenido, asignatura, unidad y usuario, y sobrescribir cada vez que se repita dicha clave.

**Comment by mweitzman** [comment]
Ese es el comportamiento actual. Esto no es un bug.
