### ISSUE TITLE
Ver profes del curso

### ISSUE THREAD

**Issue by fco96** [stesoftware/portal_fisica#38]
En la vista del buscador de asignatura al poner ver detalle no me muestra los profesores (en intro al mauro el javier es docente, debería mostrarlo a él)

Despues en la vista de mis cursos al ver los inscritos tampoco muestra al docente (el javier tambíen debería aparecer)

**Comment by mweitzman** [comment]
El comportamiento descrito está definido en la tabla de permisos. Hay que correjirlo ahí también.

**Comment by mweitzman** [comment]
Tabla de permisos actualizada, en breve el bugfix.
