### ISSUE TITLE
[Crear usuario] Tecnico

### ISSUE THREAD

**Issue by Goferk** [stesoftware/portal_fisica#53]
Al intentar crear un tecnico (desde una cuenta de tecnico) me arroja el siguiente error: 
TypeError: Cannot read property 'run' of undefined
    at m.$scope.crear (CRUD_usuario.js:56)

El run utilizado fue 19183994-5 (no se si el 5 es digito verificador)

**Comment by mweitzman** [comment]
Arreglado junto con #45
