### ISSUE TITLE
[Buscar curso] El profesor no puede

### ISSUE THREAD

**Issue by Goferk** [stesoftware/portal_fisica#54]
Arroja error 503 al buscar curso por semestre siendo profesor (semestre 2)
Arroja error 503 al buscar curso por año siendo profesor (2016)
Arroja error 503 al buscar curso por sede (CSJ)

**Comment by mweitzman** [comment]
Seguí los pasos y no pude replicar.

**Comment by fco96** [comment]
Idem, no pude replicar el error :/
