### ISSUE TITLE
[Contenido] Error al cargar contenido

### ISSUE THREAD

**Issue by fco96** [stesoftware/portal_fisica#55]
En la consola se muestra este error 
> angular.min.js:118 Error: [$sce:unsafe]...(sigue arto más de texto)

Igual muestra los contenidos que existen
Estoy viendo los contenidos de este url
>https://stesoft.tech/#/inscripcion/10/unidad/16

**Comment by mweitzman** [comment]
La descripción es poco clara y no permite replicar el error.

**Comment by mweitzman** [comment]
Al parecer es un bug de angular, de todos modos, no impide el uso de links y/o referencias externas. Arreglarlo considerando la cantidad de bugs parece innecesario.
