### ISSUE TITLE
[Vista Unidades] Profesor Docente y Coordinador

### ISSUE THREAD

**Issue by Goferk** [stesoftware/portal_fisica#56]
El profesor inscrito en un curso (como docente o coordinador) no puede ver el listado de unidades (No arroja error, solo no muestra nada)

**Comment by fco96** [comment]
Las querys no retornan nada si es que uno es 
> alumno, docente o coordinador

Probrablemente el problema esta en la api de unidad

**Comment by Goferk** [comment]
Tampoco permite ver mayores rangos que alumno si es que es un alumno el que revisa inscritos
